package pl.lodz.p.microservices.proxy.mongo;

enum Methods {
    GET_SERVICES_LIST,
    GET_SERVICE_DETAILS,
    SAVE_NEW_SERVICE,
    DELETE_SERVICE,
    EDIT_SERVICE,
    DELETE_BOOKING,
    SAVE_NEW_BOOKING,
    GET_BOOKINGS_LIST,
    GET_BOOKING_DETAILS,
    EDIT_BOOKING
}