version: "2"

services:
  mongodatabase:
    image: microservices/mongodatabase:latest
    volumes:
     - /data/db/bookings:/data/db
    restart: always

  mongobookingdatabaseproxy:
    image: microservices/mongobookingdatabaseproxy:latest
    links:
      - mongodatabase
    restart: always

  mongoservicesdatabaseproxy:
    image: microservices/mongoservicesdatabaseproxy:latest
    links:
      - mongodatabase
    restart: always

  mongousersdatabase:
    image: microservices/mongousersdatabase:latest
    volumes:
     - /data/db/users:/data/db
    restart: always

  mongousersdatabaseproxy:
    image: microservices/mongousersdatabaseproxy:latest
    links:
      - mongousersdatabase
    restart: always

  servicesmanagement:
    image: microservices/servicesmanagement:latest
    restart: always

  usersmanagement:
    image: microservices/usersmanagement:latest
    restart: always

  bookingmanagement:
    image: microservices/bookingmanagement:latest
    restart: always

  authservice:
    image: microservices/authservice:latest
    restart: always

  restapi:
    image: microservices/restapi:latest
    ports:
          - "8094:8094"
    restart: always

  frontend:
    image: microservices/frontend:latest
    ports:
          - "80:80"
    restart: always