package pl.lodz.p.microservices.proxy.mongo;

enum Methods {
    GET_SERVICES_LIST_FROM_DATABASE,
    GET_SERVICE_DETAILS_FROM_DATABASE,
    SAVE_NEW_SERVICE_IN_DATABASE,
    DELETE_SERVICE_FROM_DATABASE,
    EDIT_SERVICE_IN_DATABASE
}