package pl.lodz.p.microservices.proxy.mongo;

enum Methods {
    DELETE_BOOKING_FROM_DATABASE,
    SAVE_NEW_BOOKING_IN_DATABASE,
    GET_BOOKINGS_LIST_FROM_DATABASE,
    GET_BOOKING_DETAILS_FROM_DATABASE,
    EDIT_BOOKING_IN_DATABASE,
    GET_TAKEN_DATES_FROM_DATABASE,
    DELETE_USER_BOOKINGS_FROM_DATABASE
}